# Generated by Django 4.2.4 on 2023-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rpassword',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
