# Generated by Django 4.2.4 on 2023-09-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user_comment',
        ),
    ]
