# Generated by Django 4.2.4 on 2023-09-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_author_comment_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='author',
        ),
    ]
