# Generated by Django 4.2.4 on 2023-09-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_user_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
