# Generated by Django 4.2.4 on 2023-09-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
