# Generated by Django 4.2.4 on 2023-09-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',)},
        ),
    ]
