# Generated by Django 4.2.4 on 2023-10-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
