# Generated by Django 4.2.4 on 2023-08-31 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_aa_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AA',
            new_name='Order',
        ),
    ]
