# Generated by Django 4.2.4 on 2023-08-31 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order_2',
        ),
    ]
