# Generated by Django 4.2.4 on 2023-08-31 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_rename_order_order_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_2',
        ),
    ]
