# Generated by Django 4.2.4 on 2023-09-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='user',
        ),
    ]
